### ISSUE TITLE
No innoDB for TPCC database testing?

### ISSUE THREAD

**Issue by X1anWang** [edgelesssys/edgelessdb#78]
Hi,

**My goal.** To condect TPCC test (link-1 [https://github.com/Percona-Lab/tpcc-mysql](url)) for edgelessdb.
**My approach.** Edgelessdb SIM mode, Linux remote server with ubuntu 16.04.
**The problem.** The create_table.sql from link-1 requires innoDB engines, but I find there are rocksDB, etc. but no innoDB engines by checking 'show engines;' (however, my original local mysql has innoDB).
**My trials.** I wanted to make up the innoDB for my task and decided to install innoDB through MySQL plugin. I entered my-edb and executed 'mysql> show variables like "show variables like plugin_dir"' and got "/usr/local/mysql/lib/plugin", but there is no such directors on the server.

I am very glad that if anyone could tell me if it is because of my operations or the limitations of edgelessDB, and most importantly, how I can install innoDB for my TPCC testing?

Thanks very much : )

**Comment by thomasten** [comment]
Hi, currently EdgelessDB supports RocksDB only because the enhanced encryption is implemented at storage engine level. (See [introduction of the Readme](https://github.com/edgelesssys/edgelessdb#edgelessdb).) We're considering to add a generic encryption layer that would work with all engines, but there's no ETA yet.
